dist: xenial

language: php

addons:
    code_climate:
        repo_token: 3b0878715671c2e346688330ab3b1f96c9f92b722d5bd9b4d2901fb39e6698b2

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: 8.0
          before_script:
            - rm composer.json
            - mv composer-8.json composer.json

before_install:
    - sudo apt-get update
    - sudo apt-get install -y php-gd

install:
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - vendor/bin/test-reporter
