language: php

addons:
    code_climate:
        repo_token: 3b0878715671c2e346688330ab3b1f96c9f92b722d5bd9b4d2901fb39e6698b2

dist: trusty

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.4
    - 8.0

before_install:
    - composer self-update

install:
    - rm composer.json
    - mv composer.travis.json composer.json
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - vendor/bin/test-reporter
